name: leveldb
description: LevelDB dart bindings
version: 1.0.1
author: Adam Lofts <adam.lofts@gmail.com>
homepage: https://github.com/adamlofts/leveldb_dart
dependencies:
dev_dependencies:
  test: "^0.12.6"
