name: leveldb
description: Dart bindings for the LevelDB key value store.
version: 6.0.0
author: Adam Lofts <adam.lofts@gmail.com>
homepage: https://github.com/adamlofts/leveldb_dart
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6
dev_dependencies:
  test: ^1.3.0
