name: rocksdb
description: Dart bindings for the RocksDB key-value store.
version: 0.1.0
author: Nathan Fiedler <nathanfiedler@fastmail.fm>
homepage: https://github.com/nlfiedler/dart-rocksdb

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  path: ^1.6.4
  pedantic: ^1.8.0
  test: ^1.6.0
