name: leveldb
description: LevelDB dart bindings
version: 3.0.0-beta
author: Adam Lofts <adam.lofts@gmail.com>
homepage: https://github.com/adamlofts/leveldb_dart
dependencies:
dev_dependencies:
  test: "^0.12.20+10"
